stx_croissants_home:
    path:     /{date}
    defaults: { _controller: STXCroissantsBundle:Croissants:home, date : null }
    requirements:
        date: \d+
    options:
        expose: true
    
stx_croissants_subscribe:
    path: /subscribeCroissant
    defaults: { _controller: STXCroissantsBundle:Croissants:subscribeCroissant }
    methods : [POST]
        
stx_croissants_unsubscribe:
    path: /unsubscribeCroissant
    defaults: { _controller: STXCroissantsBundle:Croissants:unsubscribeCroissant }
    methods : [POST]
        
stx_croissants_confirmuser:
    path: /confirmUser
    defaults: { _controller: STXCroissantsBundle:Croissants:confirmUser }
    methods : [POST]
        
stx_croissants_updateremark:
    path: /updateRemark
    defaults: { _controller: STXCroissantsBundle:Croissants:updateRemark }
    methods : [POST]

stx_croissants_subscriberlist:
    path: /subscriberlist/{date}
    defaults: { _controller: STXCroissantsBundle:Croissants:subscriberlist, date : null }
    requirements:
        date: \d+
    options:
        expose: true

stx_croissants_list:
    path:     /list
    defaults: { _controller: STXCroissantsBundle:Croissants:list }
    
stx_croissants_prefs:
    path:     /prefs
    defaults: { _controller: STXCroissantsBundle:Croissants:prefs }
    
stx_croissants_stats:
    path:     /stats
    defaults: { _controller: STXCroissantsBundle:Croissants:stats }

stx_croissants_admin_mail:
    path:     /admin/mail
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:mail }
    
stx_croissants_admin_holidays:
    path:     /admin/holidays
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:holidays }

stx_croissants_admin_holidaylist:
    path: /admin/holidaylist
    defaults: { _controller: STXCroissantsBundle:Croissants:holidaylist }
    options:
        expose: true
    
stx_croissants_admin_deleteholiday:
    path: /admin/deleteholiday
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:deleteHoliday }
    methods : ['POST']
    
stx_croissants_admin_admin:
    path:     /admin/admin
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:admin }

stx_croissants_admin_importusers:
    path:     /admin/importusers
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:importusers }
    
stx_croissants_admin_testpage:
    path:     /admin/testpage
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:testpage }
    
stx_croissants_admin_test1:
    path:     /admin/test1
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:test1 }
    methods : [POST]
        
stx_croissants_admin_test2:
    path:     /admin/test2
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:test2 }
    methods : [POST]
        
stx_croissants_admin_test3:
    path:     /admin/test3
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:test3 }
    methods : [POST]
        
stx_croissants_admin_insert_subscription:
    path:    /admin/insertsubscription
    defaults: { _controller: STXCroissantsBundle:CroissantsAdmin:insertsubscription }
    